FROM basisai/workload-standard-testee

WORKDIR /test

COPY ./test.sh ./test.py requirements-test.txt /test/

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements-test.txt

CMD ["python3", "test.py"]
